<?php
/**
  * Implementation of hook_menu()
  */
function fb_ac_menu() {
  $items['admin/settings/fb_ac'] = array(
      'title' => 'Facebook AC Settings',
      'description' => 'Setting facebook app detail',
      'access arguments' => array('administer site configuration'),
      'page callback' => 'drupal_get_form',
      'page arguments' => array('fb_util_settings_form'),
      'type' => MENU_NORMAL_ITEM,
      'file' => 'fb_ac.admin.inc'
  );
  return $items;
}
function _validate_facebook_session($args, $app_secret) {
  $payload = '';
  ksort($args);
  foreach ($args as $key => $value) {
    if ($key != 'sig') {
      $payload .= $key . '=' . $value;
    }
  }
  $hash_in = $payload . $app_secret;
  $sig = $args['sig'];
  if (md5($hash_in) != $sig) {
    return null;
  }
  return $args;
}



